# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Kadai16-MVVM' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Kadai16-MVVM
pod 'SwiftLint'
end
